A = """INSERT INTO T1 (title, description, keywords, web) VALUES( 'Malabar Limited - Costumes, Dancewear & Make-up', 'Your source for costumes, dancewear and make-up since 1923!', 'toronto,canada,ontario,ottawa,nepean,costume,costumes,costume rental,Toronto,Malabar Limited, malabars,malibar,malibars,theatrical,theatre,costume,costumes,costume rental,opera,wardrobe,danceware,dancewear,wigs,theatrical makeup,spfx,spfx makeup,masks,drama,show business,ballet,dance,dance shoes,halloween,halloween costumes,POINTE SHOES,BALLET SHOES,Freed, 
              Angelo Luzio,Grishko,Sansha,Bloch,Principal,SWING SHOES,Angelo 
              Luzio,Capezio,TAP SHOES,CHARACTER SHOES,Capezio,Angelo Luzio,Angelo 
              Luzio,DANCE SNEAKERS,Bloch,Capezio,Mondor,Danskin,Mondor Danskin,Bal Togs,ACCESSORIES,Body Stockings,Head 
              Bands,Waistbelts,Legwarmers Dance Briefs,Rosin,Dance Magazine,
             tights, leotards,tutu,Mirella,Body Wrappers, 
              Principal Nylon Warmups, Thera Band, Bun Head's Pointe Shoe Accessories, 
              Principal R.A.D Canvas Character Shoes, KD Dance Knitwear,Ben Nye,Kryolan 
              ,Mehron,Manic Panic,Pro Knows,Scarecrow,Graftobian,Tiaras,Boas,Gloves,Hats,Feather 
              Masks Novelties,wigs,SPFX contact lenses, SPFX contacts, contact lenses, contacts, halloween contacts, halloween contact lenses,prosthetic, prosthetics, liquid latex, neutral mask, plain white mask,clown, clown nose,', 'http://www.malabar.net');"""

print(A)
A = A.strip("\t")
print("------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------")
print(A)